name = "telegram-github-worker"
main = "src/index.ts"
compatibility_date = "2025-04-21"

[vars]
DEBUG = ""

[[kv_namespaces]]
binding = "TG_GH_KV"
id = "KV_ID_PLACEHOLDER"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
