name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: npm ci

      - run: npm run typecheck

      - run: npm test

      - name: Set KV namespace ID
        run: sed -i "s/KV_ID_PLACEHOLDER/${{ secrets.KV_ID }}/" wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_EDIT_WORKER_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
